#!/usr/bin/env ruby
require 'json'
require 'yaml'
require 'uri'

filename = ARGV.first
puts filename
destination = filename.sub("data/", "docs/_pages/").sub(".yaml", ".md")
input = File.read(filename)
yaml = YAML.load(input)

description = yaml["description"].sub "\n", "\n\n"
name = yaml["attributes"]["binomial name"] || yaml["attributes"]["trinomial name"]
yaml["permalink"] = yaml["category"].join("/") + "/" + name.downcase.gsub(" ", "_").gsub(".", "").gsub("''", "").gsub("(", "-").gsub(")", "") + ".html"
yaml["layout"] = "page"
yaml["title"] = yaml["name"]

yaml.delete("description")
yaml.delete("name")

for index in (0...yaml["images"].length)
  yaml["images"][index]["path"] = URI.parse(yaml["images"][index]["src"]).path
end

File.open(destination, 'w') { |f| 
  f.write yaml.to_yaml()
  f.write "\n---\n"
  f.write description
}
