#!/usr/bin/env ruby
require 'json'
require 'yaml'

filename = ARGV.first
puts filename
destination = filename.sub("data/", "docs/_pages/").sub(".yaml", ".md")
input = File.read(filename)
yaml = YAML.load(input)

description = yaml["description"].sub "\n", "\n\n"
name = yaml["attributes"]["binomial name"] || yaml["attributes"]["trinomial name"]
yaml["permalink"] = yaml["category"].join("/") + "/" + name.downcase.gsub(" ", "_").gsub(".", "").gsub("''", "") + ".html"
yaml["layout"] = "page"
yaml["title"] = yaml["name"]

yaml.delete("description")
yaml.delete("name")

File.open(destination, 'w') { |f| 
  f.write yaml.to_yaml()
  f.write "\n---\n"
  f.write description
}
